//AUTH
export const authConstants = {
    SIGN_IN: "SIGN_IN",
    SIGN_OUT: "SIGN_OUT",
    CREATE_ACCOUNT: "CREATE_ACCOUNT",
    SET_USER: "SET_USER"
};

// POPUP
export const popupConstants = {
    SHOW_CREATE_STUDY_GROUP_POPUP: "SHOW_CREATE_STUDY_GROUP_POPUP",
    SHOW_JOIN_STUDY_GROUP_POPUP: "SHOW_JOIN_STUDY_GROUP_POPUP",
    SHOW_EDIT_STUDY_GROUP_POPUP: "SHOW_EDIT_STUDY_GROUP_POPUP",
    SHOW_INPUT_POPUP: "SHOW_INPUT_POPUP",
    CLOSE_POPUP: "CLOSE_POPUP"
};

//AUTH
export const studyGroupsConstants = {
    ADD_STUDY_GROUP: "ADD_STUDY_GROUP",
    LOAD_STUDY_GROUPS: "LOAD_STUDY_GROUPS",
    POPULATE_SEARCH: "POPULATE_SEARCH"
};

//NOTIFICATIONS
export const notificationConstants = {
    SHOW_ERROR_NOTIFICATION: "SHOW_ERROR_NOTIFICATION",
    SHOW_SUCCESS_NOTIFICATION: "SHOW_SUCCESS_NOTIFICATION",
    HIDE_NOTIFICATION: "HIDE_NOTIFICATION"
};
